name: Deploy AWS SAM App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM app
        run: sam build

      - name: Deploy SAM app
        run: sam deploy --no-confirm-changeset --stack-name aws-iot-sam-stack --capabilities CAPABILITY_IAM
